apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mongo-express
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - mongo-express-01.docker.localhost
    - mongo-express-02.docker.localhost
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - mongo-express-01.docker.localhost
    - mongo-express-02.docker.localhost
    tls:
      mode: SIMPLE # enables HTTPS on this port
      serverCertificate: /etc/certs/servercert.pem
      privateKey: /etc/certs/privatekey.pem
